Agenda:Meeting.o Date.o User.o Storage.o
	g++ -std=c++0x -o Agenda.o

Storage.o:Storage.h Storage.cpp
	g++ -std=c++0x -c Storage.cpp

Meeting.o:Meeting.h Meeting.cpp
	g++ -std=c++0x -c Meeting.cpp



User.o:User.h User.cpp
	g++ -std=c++0x -c User.cpp

Date.o:Date.h Date.cpp
	g++ -std=c++0x -c Date.cpp

clean:
	rm -f *.o
